### ISSUE TITLE
gribi/proto/service/gribi.proto missing key information

### ISSUE THREAD

**Issue by jihoonyoon** [openconfig/gribi#1]
Below is part of gribi.proto file. Ipv4Entry, ipv6Entry, and all appear to be missing key information. If my understanding is correct, they should be Ipv4EntryKey, Ipv6EntryKey, and so on.

        oneof entry {
          gribi_aft.Afts.Ipv4Entry ipv4 = 4;
          gribi_aft.Afts.Ipv6Entry ipv6 = 5;
          gribi_aft.Afts.LabelEntry mpls = 6;
          gribi_aft.Afts.NextHopGroup next_hop_group = 7;
          gribi_aft.Afts.NextHop next_hop = 8;
        }

**Comment by robshakir** [comment]
Thanks, this was fixed in an internal branch a while ago and in this repo when upstreamed.
