### ISSUE TITLE
Server initiated connection termination

### ISSUE THREAD

**Issue by rambattu** [openconfig/gribi#10]
https://github.com/openconfig/gribi/blob/40372e8b4395934f2ebfd30c39615e42dc383f2c/v1/proto/service/gribi.proto#L108

  // If the client redundancy mode is ALL_PRIMARY, but a client
  // sends election_id, **_the network element closes the connection
  // to the client_** and responds with FAILED_PRECONDITION in
  // status.proto's `code` and sets ModifyRPCErrorDetails.reason
  // to ELECTION_ID_IN_ALL_PRIMARY

When a client makes an invalid request via `ModifyRequest` message, is the server endpoint supposed to terminate the client connection after sending an error status?

In almost all the gRPC server examples I have looked, the server has only RPC specific context, don't see a mechanism to initiate disconnection of the client. Is there any gRPC example where the server initiates the client termination as well after sending error on the RPC, that would be helpful for reference.

**Comment by nandanarista** [comment]
> https://github.com/openconfig/gribi/blob/40372e8b4395934f2ebfd30c39615e42dc383f2c/v1/proto/service/gribi.proto#L108
> 
> // If the client redundancy mode is ALL_PRIMARY, but a client
> // sends election_id, **_the network element closes the connection // to the client_** and responds with FAILED_PRECONDITION in
> // status.proto's `code` and sets ModifyRPCErrorDetails.reason
> // to ELECTION_ID_IN_ALL_PRIMARY
> 
> When a client makes an invalid request via `ModifyRequest` message, is the server endpoint supposed to terminate the client connection after sending an error status?
> 
> In almost all the gRPC server examples I have looked, the server has only RPC specific context, don't see a mechanism to initiate disconnection of the client. Is there any gRPC example where the server initiates the client termination as well after sending error on the RPC, that would be helpful for reference.

This is referring to the server's RPC handler returning with an error which will close the stream for that Modify.
See the reference server implementation in [gribigo](https://github.com/openconfig/gribigo).

[`checkParams`](https://github.com/openconfig/gribigo/blob/8a7b2b5e41b552a5cf447e4bff41cb8f83489f55/server/server.go#L427) creates the errdetails and it is returned in [`Modify()`](https://github.com/openconfig/gribigo/blob/8a7b2b5e41b552a5cf447e4bff41cb8f83489f55/server/server.go#L319)

Maybe we can reword the text you've quoted to say `closes the Modify RPC stream` instead ?

**Comment by rambattu** [comment]
Yes @nandanarista , that will greatly help because the term "connection" can be very confusing.
