### ISSUE TITLE
programming ipv4 aft entries not supported

### ISSUE THREAD

**Issue by dliu2223** [openconfig/gribi#14]
Modifying ipv4 entry as defined in the ACL.YANG is not supported in current proto, same as v6 and L2 mac entries, will they be added or the intention is to use the protobuf from ACL.YANG as input to gRIBI.  Thanks

David

     |           +--rw ipv4
     |           |  +--rw config
     |           |  |  +--rw source-address?        oc-inet:ipv4-prefix
     |           |  |  +--rw destination-address?   oc-inet:ipv4-prefix
     |           |  |  +--rw dscp?                  oc-inet:dscp
     |           |  |  +--rw dscp-set*              oc-inet:dscp
     |           |  |  +--rw protocol?              oc-pkt-match-types:ip-protocol-type
     |           |  |  +--rw hop-limit?             uint8

**Comment by robshakir** [comment]
gRIBI does not currently program ACLs, these should be changed as configuration through gNMI. 

ACL-like entries would be programmed through the `policy-forwarding` AFT in gRIBI.
