### ISSUE TITLE
import package in server.go

### ISSUE THREAD

**Issue by tsaad-dev** [openconfig/gribi#2]
Wondering if there's any additional information on running fakeserver/fakeclient?
When trying to build fakeserver, had to make below change, and then go test works.. 
Am I missing anything? much appreciated.

$ go test github.com/openconfig/gribi/fakeserver
ok      github.com/openconfig/gribi/fakeserver  0.192s

diff --git a/fakeserver/server.go b/fakeserver/server.go
index d6d1fd7..0eed829 100644
--- a/fakeserver/server.go
+++ b/fakeserver/server.go
@@ -20,13 +20,13 @@ import (
        "context"
        "sync"

-       "gob/gribi/oc"
+       "github.com/openconfig/gribi/oc"

        "github.com/openconfig/ygot/ygot"
        "google.golang.org/grpc/codes"
        "google.golang.org/grpc/status"

-       rpb "gob/gribi/proto/service"
+       rpb "github.com/openconfig/gribi/proto/service"

        gpb "github.com/openconfig/gnmi/proto/gnmi"
 )
diff --git a/fakeserver/server_test.go b/fakeserver/server_test.go
index 46edb2e..61e3bfa 100644
--- a/fakeserver/server_test.go
+++ b/fakeserver/server_test.go
@@ -30,7 +30,7 @@ import (
        "google.golang.org/grpc/reflection"
        "google.golang.org/grpc/status"

-       rpb "gob/gribi/proto/service"
+       rpb "github.com/openconfig/gribi/proto/service"

        gpb "github.com/openconfig/gnmi/proto/gnmi"
 )

**Comment by robshakir** [comment]
Fixed in #5, thanks.
