### ISSUE TITLE
Not sending election message in SINGLE PRIMARY mode should be an error

### ISSUE THREAD

**Issue by VijayKestur** [openconfig/gribi#24]
https://github.com/openconfig/gribi/blob/386ca81f79d0c872be9667ec8021a48b4d870ee3/v1/proto/service/gribi.proto#L450

If election message is missing in the Flush request (neither id nor override is set), it will be good to send an error from server. A new error for this needs to be defined.

If override is set to FALSE, this should also be an error and a new value needs to be defined in FlushResponseError Reason enum.

**Comment by robshakir** [comment]
This was fixed in #23 and #25.
