### ISSUE TITLE
Programming nexthop with mac-address

### ISSUE THREAD

**Issue by mohanasm** [openconfig/gribi#52]
For programming AFT nexthop with mac-address, are there any restrictions in using reserved mac-address , like 01:80:C2:XX:XX:XX, 00-00-5E-XX-XX-XX? Since these mac addresses are not meant for data packets and may be interpreted as PDU in pre-classification in receiving node, is it recommended to add restriction for such reserved mac address range? 

https://github.com/openconfig/gribi/blob/63905fc23f56e1f708c85a09890ea4a60b8be559/v1/proto/gribi_aft/gribi_aft.proto#L88

**Comment by earies** [comment]
The proto is autogenerated from `openconfig-aft-ethernet` and the leaf uses an unrestricted `oc-yang:mac-address` type

```
    leaf mac-address {
        type oc-yang:mac-address;
        description
          "The outer MAC address of the Ethernet frame that must
          be matched for the AFT entry to be utilised.";
    }
```

So the YANG model and by nature the generated proto allow for the entire 48-bit range.  Any restrictions imo would need to be drawn by way of specification and/or backend validation (and implementation documentation)

**Comment by xw-g** [comment]
re @mohanasm, in addition to @earies's https://github.com/openconfig/gribi/issues/52#issuecomment-1137872362, I think it's the client's responsibility to populate the "correct" mac-address in the nex-hop message. Hence, I feel like we probably don't need to enforce extra validation here. This is kinda of aligned with https://github.com/openconfig/gribi/blob/master/doc/motivation.md#logic-for-limited-validation

**Comment by mohanasm** [comment]
Thanks @earies and @xw-g for the clarification!

**Comment by xw-g** [comment]
Thanks for raising the questions!
