### ISSUE TITLE
Add IPv4 entries that are resolved by NHG and NH, in random order

### ISSUE THREAD

**Issue by shireeshbhat** [openconfig/gribi#69]
In the HLD document in section TE-3 (Support for Hierarchical Lookups) it is mentioned that the NHGs and NHs will be sent in a single ModifyRequest. The test case and the requirement in the HLD seems to be contradictory. Can you please clarify?

**Comment by dplore** [comment]
Can you add a link to the source which is in question?

**Comment by dplore** [comment]
Is this the portion of the code where you see the randomization?  https://github.com/openconfig/gribigo/blob/main/compliance/compliance.go#L561

**Comment by dplore** [comment]
@xw-g the specific issue is whether or not these entries should be random or in-order.  Currently https://github.com/openconfig/gribigo/blob/484488bcca14e705ddc045050239167054200dff/compliance/compliance.go#L561 is set to random and our requirements say in order.  Should we change this?

**Comment by LimeHat** [comment]
Hi Darren & Xiao @dplore @xw-g ,
I'm not the original author of this question but have a similar q.: if we assume that entries are sent in-order, there are (potentially) two ways of doing this:
1) send NH+NHG (and potentially IP entry) as a single modify request with two or more operations, or
2) send each operation as a separate modify request, e.g. first send a NH, then a NHG, then an IP entry

Is it assumed that both 1) and 2) are expected to be supported in all implementations, i.e. even for in-order entries NH + NHG can be sent as a separate requests? Compliance test cases seem to imply so
