### ISSUE TITLE
Return status on hardware error and interface in down state.

### ISSUE THREAD

**Issue by deepak-jnpr** [openconfig/gribi#79]
https://github.com/openconfig/gribi/blob/595c2f2e3c1635f75dc79cc97eddf62720990f1d/v1/proto/service/gribi.proto#L286

1. In case of hardware error while programming a route, should gRIBI ModifyResponse contain AFTResult with FIB_FAILED or FAILED? (Comment suggests FAILED in line 286).
2. If Nexthop is programmed with interface in down state, should AFTResult be FIB_FAILED or RIB_PROGRAMMED.

**Comment by xw-g** [comment]
1. `hardware error while programming` implies that the entry has been accepted/installed in the RIB and being pushed to the FIB, therefore it should be a `FIB_FAILED` not `FAILED`. 
2. If the injected nexthop contains all the needed information for forwarding resolution (e.g. egress port and destination mac address), we expect it to be `FIB_PROGRAMMED` even the interface is down. Basically we are saying that `FIB_PROGRAMMED` != forwarding viable in the case of NH object. 

If you have more questions, we can discuss offline. BTW: we plan to update the spec with more clarification related to `FIB_FAILED`, which should cover above questions.

**Comment by aredmon8551** [comment]
@xw-g - are you referring to an instance in which the MAC is learned through gRIBI and not through ARP?

**Comment by xw-g** [comment]
Shall we have an offline discussion? I sensed there might be some gaps in your understanding of the use case. Thanks.

**Comment by deepak-jnpr** [comment]
Issue cleared.

**Comment by sachendras** [comment]
Can we please provide some update on the final consensus for posterity?
