### ISSUE TITLE
Specification of GetRequest/FlushRequest does not mention "network_instance all" option

### ISSUE THREAD

**Issue by LimeHat** [openconfig/gribi#82]
In the [specification.md](https://github.com/openconfig/gribi/blob/e88a095e6fe2bccbf688f6be40348a1108592bd0/doc/specification.md) both GetRequest message (section 4.2.1) and FlushRequest message (section 4.3.1) explicitly mention that network-instance name has to be specified; however, in proto files, we can see that network_instance is [defined as oneof name/all](https://github.com/openconfig/gribi/blob/e88a095e6fe2bccbf688f6be40348a1108592bd0/v1/proto/service/gribi.proto#L449):
```
  oneof network_instance {
    // The network instance from which the entries should be retrieved.
    // If `network_instance` is nil (`name` and `all` not specified),
    // or if `name` is specified and it is the empty string "",
    // then the request is considered invalid and the server should
    // respond with the INVALID_ARGUMENT error code in the status.proto
    // carried along with the RPC response.
    string name = 1;
    // all indicates that entries for all network instances for the
    // should be returned.
    Empty all = 2;
  }

```

Could you please clarify what is the expected behavior going forward, i.e. should the spec be updated to support "all" flag, or "all" is going to be eventually deprecated?

Thanks,

**Comment by robshakir** [comment]
`all` is intended to be kept. The requirement for the network instance name is because we do not allow `""` to mean the default instance -- so setting this `oneof` to `name = ""` is what is disallowed by the spec clarification.
